### ISSUE TITLE
How to implement asynchronous calls

### ISSUE THREAD

**Issue by itviewer** [Cutehacks/duperagent#11]
In your sample code, ui is blocked，the request is executed synchronously

**Comment by jrbarron** [comment]
@itviewer Can you elaborate on this? Internally the requests are made using `QNetworkAccessManager` which only offers an asynchronous API so sending the actual request will definitely not block the UI. In my sample code, the function passed as a callback in `end()` executes asynchronously, but if you do a lot of computation in here, then it could potentially block the UI since Javascript has to execute in the same thread as the UI unfortunately. Perhaps a Worker could help mitigate this, but I have not tried this myself.

**Comment by itviewer** [comment]
Hi, @jrbarron ,
what I did is just follow the QtCreator Wizard，created a QtQuick controls2 application，then include this repository，and add this code to main.qml
```
    Component.onCompleted: {
        Http.request
            .get("https://api.vultr.com/v1/os/list")
            .end(function(err, res) {
                console.log(JSON.stringify(res.body));
            });
    }
```
(For convenience, I uploaded it to https://github.com/itviewer/example )
if no this code，the application interface immediately displayed，but after add the code，the interface is blank when the application starts, and the mouse is busy state.

then I tried **XMLHttpRequest**，it has the same result. now I suspect that the problem is not **duperagent** or **XMLHttpRequest**, should we not write request code in `Component.onCompleted`?

Thanks, I will be so grateful for your help

**Comment by itviewer** [comment]
Ithink the problem may be in the main.cpp
the default created QtQuick application in the main.cpp is
```
#include <QGuiApplication>
#include <QQmlApplicationEngine>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));
    if (engine.rootObjects().isEmpty())
        return -1;

    return app.exec();
}
```
after changed to
```
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQuickView>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));
    if (engine.rootObjects().isEmpty())
        return -1;

    QObject* root = engine.rootObjects().at(0);
    static_cast<QQuickWindow*>(root)->show();

    return app.exec();
}
```
the application interface immediately displayed and the http request  also work well.

**Comment by jrbarron** [comment]
Closing this as it doesn't appear to be an issue with Duperagent.
