### ISSUE TITLE
Cache control per request

### ISSUE THREAD

**Issue by Max-Might** [Cutehacks/duperagent#15]
Hello.

Thanks for sharing this library, it's awesome.

I have been wondering if it would be possible to control cache save/load per request.
The `QNetworkRequest` class has some attributes for this purpose: `QNetworkRequest::CacheSaveControlAttribute` and `QNetworkRequest::CacheLoadControlAttribute`.

**Comment by jrbarron** [comment]
Hi @Max-Might, thanks for the feedback! Really glad that you find it useful.

It should definitely be possible to add an option for that. Do you have any suggestions for an API? If not, I can give it some thought and see if I can come up with something sensible. You're also very welcome to send a PR for this feature if you feel like it ;)

**Comment by Max-Might** [comment]
For cache saving we could have `.cacheSave(true/false)`.

For cache loading we could have `.cacheLoad(Http.CacheControl.AlwaysCache)` for example.
We will need defines for all items in the `QNetworkRequest::CacheLoadControl` enum that is needed as a parameter for `cacheLoad()`.

What do you think?
