### ISSUE TITLE
calls to `request` singleton type fail in Qt 5.9.5

### ISSUE THREAD

**Issue by marco-piccolino** [Cutehacks/duperagent#17]
Probably due to the QML type being lower case?
https://code.woboq.org/qt5/qtdeclarative/src/qml/qml/qqmlmetatype.cpp.html#1572

**Comment by jrbarron** [comment]
Yes, I think this is already fixed in Duperagent v1.5.0. Now I register both upper and lower case names. If you are using the versions of Qt (5.10.x?) that requires the upper casing, you should upgrade and start using `Http.Request`. Can you confirm this works?

**Comment by jrbarron** [comment]
Closing this one for now. Please re-open if this is still an issue 😉
