### ISSUE TITLE
some tests failing with latest Qt 5.11.1

### ISSUE THREAD

**Issue by rmallah** [Cutehacks/duperagent#19]
Hi , 

Below tests are found to be failing . 
Not sure if its due to changes to Qt.

./tst_duperagent
********* Start testing of duperagent *********
Config: Using QtTest library 5.11.1, Qt 5.11.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))

FAIL!  : duperagent::httpbin::test_ssl() Compared values are not the same
   Actual   (): 5f:f1:60:31:09:04:3e:f2:90:d2:b0:8a:50:38:04:e8:37:9f:bc:76
   Expected (): 35:85:74:ef:67:35:a7:ce:40:69:50:f3:c0:f6:80:cf:80:3b:2e:19
   Loc: [/mnt/khajana/Qt/Projects/NG/duperagent/tests/tst_duperagent.qml(638)]
FAIL!  : duperagent::imageutils::test_read_props() 'wait for signal done' returned FALSE. ()
   Loc: [/mnt/khajana/Qt/Projects/NG/duperagent/tests/tst_imageutils.qml(44)]
FAIL!  : duperagent::imageutils::test_scale() Compared values are not the same
   Actual   (): undefined
   Expected (): data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD//gA+Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2ODApLCBkZWZhdWx0IHF1YWxpdHkK/9sAQwAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ0NB8nOT04MjwuMzQy/9sAQwEJCQkMCwwYDQ0YMiEcITIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy/8AAEQgAyAEKAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A+f6KKKACi
   Loc: [/mnt/khajana/Qt/Projects/NG/duperagent/tests/tst_imageutils.qml(72)]
FAIL!  : duperagent::imageutils::test_scale() 'wait for signal done' returned FALSE. ()
   Loc: [/mnt/khajana/Qt/Projects/NG/duperagent/tests/tst_imageutils.qml(77)]
 

Totals: 46 passed, 4 failed, 0 skipped, 0 blacklisted, 87906ms
********* Finished testing of duperagent *********
user01@rmallah-mac:/mnt/khajana/Qt/Projects/NG/duperagent/tests$

**Comment by jrbarron** [comment]
Fixed 😄

**Comment by rmallah** [comment]
thanks :+1:
