### ISSUE TITLE
XMLHttpRequest `arraybuffer` responseType equivalent

### ISSUE THREAD

**Issue by mohammadhasanzadeh** [Cutehacks/duperagent#21]
How can I get raw binary data, from Response like XMLHttpRequest `arraybuffer` `responseType` output?

**Comment by jrbarron** [comment]
@mohammadhasanzadeh This is not currently supported unfortunately. I think Qt now supports converting a `QByteArray` to an `ArrayBuffer` so it should technically be possible to implement this. The place where the response body parsing is done is here:

https://github.com/Cutehacks/duperagent/blob/master/response.cpp#L31-L46

Currently it is based on the content-type header. It would probably be quite simple to add handling for binary data above and just return a QByteArray (assuming Qt supports this).

To support the `responseType` behavior the way that SuperAgent does is a little more work, but this should also be doable. I can take when I get time, but if you want to send a PR, feel free!

**Comment by mohammadhasanzadeh** [comment]
Yes, I just return `data` variable as `raw` data and it works properly because Qt now supports converting `QByteArray` to `ArrayBuffer`. of course this approach not exactly is `responseType` implementation but solved my problem.

**Comment by jrbarron** [comment]
@mohammadhasanzadeh I have a patch that basically checks if the `Content-Type` is equal to `application/octet-stream` and then tries to convert the byte array to an `ArrayBuffer`. Is that good enough for your use case? If not, would you mind elaborating?

**Comment by mohammadhasanzadeh** [comment]
My backend return `application/vnd.openxmlformats-officedocument.wordprocessingml.document` as `Content-type` and `attachment` as `Content-Disposition`, for this case `Content-type` not match to the `application/octet-stream`, of course I can change `Content-type`  to the `application/octet-stream`.

**Comment by mohammadhasanzadeh** [comment]
I'll try to implement `responseType` and send a PR.
