### ISSUE TITLE
add OAuth signing

### ISSUE THREAD

**Issue by marco-piccolino** [Cutehacks/duperagent#6]
Like this superagent addon:

https://github.com/LearnBoost/superagent-oauth

as to Qt libs:
https://github.com/pipacs/o2
https://github.com/ayoy/qoauth

**Comment by marco-piccolino** [comment]
oh, and of course the Qt Network Authentication upcoming module (TP in 5.8)

**Comment by jrbarron** [comment]
I started an effort around this here:

https://github.com/Cutehacks/auctor

It kinda worked well on the desktop, but needs some love on mobile. Now that Qt supports it, I'm not sure it is worth developing it further, but in any case I'll close this issue and we can discuss it on the Auctor project if so. (just doing some fall cleaning of issues 😄 )
